# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.grpc_server import evacuai_rl_pb2 as src_dot_grpc__server_dot_evacuai__rl__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in src/grpc_server/evacuai_rl_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ReinforcementLearningStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TrainModel = channel.unary_unary(
                '/rl.ReinforcementLearning/TrainModel',
                request_serializer=src_dot_grpc__server_dot_evacuai__rl__pb2.TrainRequest.SerializeToString,
                response_deserializer=src_dot_grpc__server_dot_evacuai__rl__pb2.TrainResponse.FromString,
                _registered_method=True)
        self.Inference = channel.unary_unary(
                '/rl.ReinforcementLearning/Inference',
                request_serializer=src_dot_grpc__server_dot_evacuai__rl__pb2.InferenceRequest.SerializeToString,
                response_deserializer=src_dot_grpc__server_dot_evacuai__rl__pb2.InferenceResponse.FromString,
                _registered_method=True)
        self.GetRewardPath = channel.unary_unary(
                '/rl.ReinforcementLearning/GetRewardPath',
                request_serializer=src_dot_grpc__server_dot_evacuai__rl__pb2.GetRewardPathRequest.SerializeToString,
                response_deserializer=src_dot_grpc__server_dot_evacuai__rl__pb2.GetRewardPathResponse.FromString,
                _registered_method=True)


class ReinforcementLearningServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TrainModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Inference(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRewardPath(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReinforcementLearningServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TrainModel': grpc.unary_unary_rpc_method_handler(
                    servicer.TrainModel,
                    request_deserializer=src_dot_grpc__server_dot_evacuai__rl__pb2.TrainRequest.FromString,
                    response_serializer=src_dot_grpc__server_dot_evacuai__rl__pb2.TrainResponse.SerializeToString,
            ),
            'Inference': grpc.unary_unary_rpc_method_handler(
                    servicer.Inference,
                    request_deserializer=src_dot_grpc__server_dot_evacuai__rl__pb2.InferenceRequest.FromString,
                    response_serializer=src_dot_grpc__server_dot_evacuai__rl__pb2.InferenceResponse.SerializeToString,
            ),
            'GetRewardPath': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRewardPath,
                    request_deserializer=src_dot_grpc__server_dot_evacuai__rl__pb2.GetRewardPathRequest.FromString,
                    response_serializer=src_dot_grpc__server_dot_evacuai__rl__pb2.GetRewardPathResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rl.ReinforcementLearning', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rl.ReinforcementLearning', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReinforcementLearning(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TrainModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rl.ReinforcementLearning/TrainModel',
            src_dot_grpc__server_dot_evacuai__rl__pb2.TrainRequest.SerializeToString,
            src_dot_grpc__server_dot_evacuai__rl__pb2.TrainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Inference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rl.ReinforcementLearning/Inference',
            src_dot_grpc__server_dot_evacuai__rl__pb2.InferenceRequest.SerializeToString,
            src_dot_grpc__server_dot_evacuai__rl__pb2.InferenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRewardPath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rl.ReinforcementLearning/GetRewardPath',
            src_dot_grpc__server_dot_evacuai__rl__pb2.GetRewardPathRequest.SerializeToString,
            src_dot_grpc__server_dot_evacuai__rl__pb2.GetRewardPathResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
